name: Deploy Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.s3demo30092021 }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIA2XFLL3WMCLZ7ACMZ }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.0i4j6M4O5a+Gwzgp0WGA2/04lwxBzfOo9uieT4UM }}
        AWS_REGION: 'us-east-1'   # optional: us-east-2
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
